name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
    CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: set nightly
      run: |
          rustup install nightly
          rustup default nightly

    - name: add target
      run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

    - name: add linker `lld`
      run: sudo apt-get install lld -y
      
    - name: Build
      run: make
